currenciesApi:
    path: /api/currencies/{date}
    controller: Currencies\Controller\ApiController::getAll
    defaults: { date: "" }
#    condition:  "context.getMethod() in ['GET'] and request.headers.get('Content-Type') matches '/json/i'"

index:
    path: /{wildcard}
    defaults: {
        _controller: App\Controller\DefaultController::index
    }
    requirements:
        wildcard: .*

